# fly.toml app configuration file generated for sam-kenney-blog-nameless-dew-9945 on 2024-04-04T21:03:22+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sam-kenney-blog-nameless-dew-9945'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
